# Generated by Django 3.2 on 2022-06-18 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_event_donation'),
        ('charity', '0002_remove_donation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
            preserve_default=False,
        ),
    ]
