# Generated by Django 3.2 on 2022-06-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_donation_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
