# Generated by Django 3.2 on 2022-06-18 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0010_alter_event_featured_image'),
        ('charity', '0004_delete_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('charities', models.CharField(choices=[(1, ' Consent Workshop'), (2, 'Outright International'), (3, 'Global Giving'), (4, 'Micro Rianbow')], max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Donations',
                'ordering': ['-date'],
            },
        ),
    ]
