# Generated by Django 3.2 on 2022-06-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_alter_donations_charities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='charities',
            field=models.CharField(choices=[('Consent Workshop', 'Consent Workshop'), ('Outright International', 'Outright International'), ('GlobalGiving', 'Global Giving'), ('MicroRainbow', 'Micro Rainbow')], max_length=22),
        ),
    ]
