# Generated by Django 3.2 on 2022-06-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_alter_donations_charities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='event_name',
            new_name='event',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='charities',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='email',
        ),
    ]
