# Generated by Django 3.2 on 2022-06-18 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_remove_donation_event'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='donation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.donation'),
        ),
    ]
