# Generated by Django 3.2 on 2022-06-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='donation',
        ),
    ]
