# Generated by Django 3.2 on 2022-06-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
