# Generated by Django 3.2 on 2022-06-18 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_volunteer_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug_end',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
