# Generated by Django 3.2 on 2022-06-18 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_event_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug_end',
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=uuid.uuid4),
        ),
    ]
