# Generated by Django 3.2 on 2022-06-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_event_charities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
