# Generated by Django 3.2 on 2022-06-19 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_event_volunteer_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='volunteer_list',
        ),
        migrations.AddField(
            model_name='volunteerlist',
            name='event',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
